#!/usr/bin/env node
import { createRequire } from 'module'; const require = createRequire(import.meta.url);
import L from"http";import E from"fs";import u from"path";import{fileURLToPath as N,parse as H}from"url";import{readFile as P,writeFile as j,mkdir as M}from"fs/promises";import{spawn as B,exec as G}from"child_process";import{promisify as U}from"util";import{appendFile as D}from"fs/promises";var F=[{name:"shellPath",value:"",default:{win32:"cmd.exe",darwin:"/bin/sh"}},{name:"logToFile",value:!1},{name:"logLevel",value:"error",allowedValues:["error","info","debug"]}];var O={info:t=>console.info(t),success:t=>console.info(t),debug:(...t)=>console.debug(...t),log:(...t)=>console.log(...t)},g="[[!!-!!]]";async function w({displayType:t},e){let{dateTime:n,command:o,cwd:i,commandId:s,tabId:l,status:r,processId:d,output:c}=e;if(t==2){if(F.find(_=>_.name==="logToFile").value){let _=`${n}${g}${s}${g}${o}${g}${i}${g}${r}${g}${d}${g}${c}`,m=`log-${new Date().toISOString().slice(0,10)}.txt`;await D(`./user-data/logs/${m}`,JSON.stringify(_)+`
`)}return}console.log(`[History Record]: ${o}`),console.log(`	Datetime: ${n}`),console.log(`	cwd: ${i}`),console.log(`	commandId: ${s}`),console.log(`	tabId: ${l}`)}var x=[{id:"GIT",name:"Git Operations",icon:"git",priority:1,commands:["git log -1","git status","git add .",'git commit -m "chore: update"',"git push origin","git pull origin","git log --oneline -10"],open:!1},{id:"NPM_SCRIPTS",name:"NPM Scripts",icon:"npm",priority:2,commands:["npm run dev","npm run build","npm test","npm run lint","npm install","npm ci"]},{id:"DOCKER",name:"Docker commands",icon:"docker",priority:3,commands:["docker ps","docker-compose up -d","docker-compose down","docker logs -f","docker exec -it bash"]},{id:"FILE_SYSTEM",name:"File System",icon:"fs",priority:4,commands:["ls -la","pwd",'find . -name "*.js"',"du -sh *","cat package.json","mkdir -p src/components"]}];var v=U(G),$=process.env.PORT||3434,k=u.dirname(N(import.meta.url)),C=u.join(k,"build"),W=u.join(k,"user-data"),S=new Map,y=new Map,J=[{name:"shellPath",value:"",default:{win32:"cmd.exe",darwin:"/bin/sh"}},{name:"logToFile",value:!1},{name:"logLevel",value:"error",allowedValues:["error","info","debug"]}],A=t=>{t.setHeader("Access-Control-Allow-Origin","http://localhost:3400"),t.setHeader("Access-Control-Allow-Credentials","true"),t.setHeader("Access-Control-Allow-Headers","Content-Type"),t.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS")},T=(t,e,{status:n,isPlainResponse:o}={})=>{A(t),t.writeHead(n||200,{"Content-Type":"application/json","Access-Control-Allow-Origin":"http://localhost:3400","Access-Control-Allow-Credentials":"true"}),o?t.end(e):t.end(JSON.stringify(e))},b=t=>new Promise(e=>{let n="";t.on("data",o=>n+=o),t.on("end",()=>{try{e(JSON.parse(n||"{}"))}catch{e({})}})}),X=async(t,e,n)=>{let o=process.platform==="win32",{command:i,cwd:s,requestedBy:l,id:r,tabId:d}=n;if(i==="CURRENT_WORKING_DIRECTORY"){let{stdout:c}=await v(o?"echo [[__FINAL_CWD__:%CD%]]":'echo "[[__FINAL_CWD__:$(pwd)]]"',{cwd:s||process.cwd()}),a=c.trim();return e.write(a),e.write(`
Process exited with code 0`),e.write("__PROCESS_EXITED__"),e.end()}if(i==="GIT_CURRENT_BRANCH")try{let{stdout:c}=await v("git rev-parse --abbrev-ref HEAD",{cwd:s||process.cwd()}),a=c.trim();return e.write(`
[[__FINAL_BRANCH__:${a}]]`),e.write(`
Process exited with code 0`),e.write("__PROCESS_EXITED__"),e.end()}catch(c){e.write(`
[[__ERROR__:${c.message}]]`),e.write(`
Process exited with code 0`),e.write("__PROCESS_EXITED__")}},Y=()=>{let t=J.find(e=>e.name==="shellPath");return t?.value?t?.value:t?.default?.[process.platform]??!0},V=async(t,e,n)=>{let o=process.platform==="win32",{command:i,cwd:s,requestedBy:l,id:r,tabId:d}=n,c=s||process.cwd(),a={dateTime:new Date,command:i,cwd:c,commandId:r,tabId:d,status:"started",processId:"NOT_ALLOCATED",output:""};w({displayType:2},a);let _=o?`${i} & echo [[__FINAL_CWD__:%CD%]]`:`${i}; echo "[[__FINAL_CWD__:$(pwd)]]"`,m=B(_,[],{stdio:"pipe",cwd:c,shell:Y(),env:{...process.env,FORCE_COLOR:"1",TERM:"xterm-256color"}}),f=m.pid;S.set(f,m),y.set(r,{command:i,cwd:c,tabId:d,processId:f}),a.processId=f,a.status="running",w({displayType:2},a),e.write(`[[PROCESS_ID:${f}]]
`),m.stdout.on("data",p=>{a.output=p.toString(),w({displayType:2},a),e.write("[[stdout]]"+p.toString())}),m.stderr.on("data",p=>{a.output=p.toString(),w({displayType:2},a),e.write("[[stderr]] "+p.toString())}),m.on("exit",(p,I)=>{if(I==="SIGTERM"){S.delete(f),y.delete(r);let h=`
Process exited with code ${p??I}`;e.write(h),a.status="done",a.output=h,w({displayType:2},a),e.write("__PROCESS_EXITED__"),e.end()}}),m.on("close",(p,I)=>{S.delete(f),y.delete(r);let h=`
Process exited with code ${p??I}`;e.write(h),a.status="done",a.output=h,w({displayType:2},a),e.write("__PROCESS_EXITED__"),e.end()})},q=async(t,e,n)=>{if(n.indexOf("/api/commands")>=0&&t.method==="POST"){let o=await b(t);if(n.indexOf("/api/commands/execute")>=0)return o.requestedBy==="SYSTEM"?await X(t,e,o):await V(t,e,o);if(n.indexOf("/api/commands/stop")>=0){let i=Number(o.pid),s=S.get(i);return s?(S.delete(i),y.delete(o.id),s.kill("SIGTERM"),setTimeout(()=>{s.killed||s.kill("SIGKILL")},2e3),e.write(`
Stopping the process for ${i}`),e.end()):(e.write(`
Process not found for process id: ${i}`),e.end())}}if(n.indexOf("/api/saved-folders")>=0){let o=x;return T(e,o,{isPlainResponse:typeof o=="string"})}if(n.indexOf("/api/recent-commands")>=0){let o=null,i=u.join(W,"recent","recent-commands.json");if(t.method==="POST"){let s=await b(t);try{o=await P(i,{encoding:"utf-8"}),o=JSON.parse(o)}catch{}let l="";o?(Object.keys(s).forEach(d=>{let c=[];o[d]&&(c=new Set([...o[d].cwdList,...s[d].cwdList])),s[d].cwdList=[...c],o[d]=s[d]}),l=o):l=s;let r=u.dirname(i);return await M(r,{recursive:!0}),await j(i,JSON.stringify(l,null,2),{}),T(e,{status:"ok",service:"api",version:2})}try{o=await P(i,{encoding:"utf-8"})}catch{}return T(e,o??"{}",{isPlainResponse:!0})}return T(e,{status:"ok",service:"api",version:2})},z=(t,e)=>{let n=new URL(t.url,`http://${t.headers.host}`),o=u.join(C,n.pathname);if(n.pathname==="/"&&(o=u.join(C,"index.html")),!o.startsWith(C))return e.writeHead(403),e.end("Forbidden");E.stat(o,(i,s)=>{if(i||!s.isFile())return e.writeHead(404),e.end("Not found");let l=u.extname(o),r="text/html";switch(l){case".css":r="text/css";break;case".js":r="text/javascript";break;case".json":r="application/json";break;case".png":r="image/png";break;case".jpg":r="image/jpg";break;case".html":r="text/html";break;case".icon":r="image/x-icon";break;case".svg":r="image/svg+xml";break;default:break}e.writeHead(200,{"Content-Type":r,"Content-Length":s.size}),E.createReadStream(o).pipe(e)})},Q=async(t,e)=>{if(t.method==="OPTIONS")return A(e),e.writeHead(204),e.end();let n=H(t.url,!0);return n.pathname.indexOf("/api")>=0?await q(t,e,n.pathname):z(t,e)},R=L.createServer(Q);R.listen($,()=>{O.success(`API running on http://localhost:${$}`)});R.timeout=0;R.keepAliveTimeout=0;
